# PostgreSQL. Versions 9.3 and up are supported.
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: localhost
  username: postgres
  password: postgres
  database: careerality

test:
  <<: *default
  database: server_test

production:
  primary: &primary_production
    <<: *default
    database: careerality
    username: postgres
    password: postgres
  cache:
    <<: *primary_production
    database: careerality_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: careerality_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: careerality_cable
    migrations_paths: db/cable_migrate
